PackageIdentifier: BraveSoftware.BraveBrowser
Publisher: The Brave Authors
PackageName: Brave
Moniker: Brave
ShortDescription: Secure, Fast & Private Web Browser with Adblocker
PackageUrl: https://brave.com
Tags:
- Brave
- Browser
- Chrome
- Chromium
License: Mozilla Public License 2.0
LicenseUrl: https://github.com/brave/brave-browser/blob/master/LICENSE
PackageVersion: 81.1.9.80
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.9.80/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: DCA224481AF19EBC2F97E7F8E83CBE3E7E0384FE263EA7B44B7A52D22DF75215
  InstallerSwitches:
    Silent: ""
    SilentWithProgress: ""
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
