PackageIdentifier: IrfanSkiljan.IrfanView
Publisher: Irfan Skiljan
PackageName: IrfanView
ShortDescription: IrfanView ... one of the most popular viewers worldwide.
PackageUrl: https://www.irfanview.com
Tags:
- Graphic Viewer
- Graphic Editor
PackageVersion: 4.54
License: Copyright (C) 2020 by Irfan Skiljan, Wiener Neustadt, Austria
LicenseUrl: https://www.irfanview.com/eula.htm
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://www.irfanview.mediaside.co.uk/downloads/iview454_x64_setup.exe
  InstallerSha256: CEEF2253C343902C3CE7E7CAC305F12E1123CF203660985159D9AE5B18CEAB57
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
