PackageIdentifier: BraveSoftware.BraveBrowser-Nightly
PackageVersion: 92.1.28.59
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.28.59/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 2654E8BF24549A02601627B2BB0C7D75F11614943462324F60F27995644BC82A
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.28.59/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 843F36759E0EA63F3470E3001D10CFF5AAF6F07B77F7679150CBFC143C32B242
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

