# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: 7zip.7zip
PackageVersion: 19.00.00.0
MinimumOSVersion: 10.0.0.0
Platform:
  - Windows.Desktop
FileExtensions:
  - 7z
  - XZ
  - BZIP2
  - GZIP
  - TAR
  - ZIP
  - AR
  - ARJ
  - CAB
  - CHM
  - CPIO
  - CramFS
  - DMG
  - EXT
  - FAT
  - GPT
  - HFS
  - IHEX
  - ISO
  - LZH
  - LZMA
  - MBR
  - MSI
  - NSIS
  - NTFS
  - QCOW2
  - RAR
  - RPM
  - SquashFS
  - UDF
  - UEFI
  - VDI
  - VHD
  - VMDK
  - WIM
  - XAR
  - Z
Commands:
  - 7z
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerLocale: en-US
    InstallerType: msi
    InstallerUrl: https://raw.githubusercontent.com/ip7z/a/main/7z1900-x64.msi
    InstallerSha256: A7803233EEDB6A4B59B3024CCF9292A6FFFB94507DC998AA67C5B745D197A5DC
    ProductCode: "{23170F69-40C1-2702-1900-000001000000}"
    Scope: machine
    UpgradeBehavior: install
  - Architecture: x64
    InstallerLocale: en-US
    InstallerType: nullsoft
    InstallerUrl: https://raw.githubusercontent.com/ip7z/a/main/7z1900-x64.exe
    InstallerSha256: 0f5d4dbbe5e55b7aa31b91e5925ed901fdf46a367491d81381846f05ad54c45e
    Scope: machine
    UpgradeBehavior: install
  - Architecture: x86
    InstallerLocale: en-US
    InstallerType: msi
    InstallerUrl: https://raw.githubusercontent.com/ip7z/a/main/7z1900.msi
    InstallerSha256: B49D55A52BC0EAB14947C8982C413D9BE141C337DA1368A24AA0484CBB5E89CD
    ProductCode: "{23170F69-40C1-2701-1900-000001000000}"
    Scope: machine
    UpgradeBehavior: install
  - Architecture: x86
    InstallerLocale: en-US
    InstallerType: nullsoft
    InstallerUrl: https://raw.githubusercontent.com/ip7z/a/main/7z1900.exe
    InstallerSha256: 759aa04d5b03ebeee13ba01df554e8c962ca339c74f56627c8bed6984bb7ef80
    Scope: machine
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
