PackageIdentifier: 7zip.7zip
PackageName: 7-Zip
Moniker: 7zip
PackageVersion: 16.0.4
Publisher: Igor Pavlov
Author: Igor Pavlov
License: Copyright (C) 1999-2020 Igor Pavlov. - GNU LGPL
LicenseUrl: https://7-zip.org/license.txt
MinimumOSVersion: 10.0.0.0
PackageUrl: https://www.7-zip.org/
ShortDescription: Free and open source file archiver with a high compression ratio.
Tags:
- 7zip
- compression
- file compression
- utility
- tool
- zip
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://www.7-zip.org/a/7z1604-x64.msi
  InstallerSha256: B3885B2F090F1E9B5CF2B9F802B07FE88E472D70D60732DB9F830209AC296067
  InstallerSwitches:
    Silent: /quiet /norestart
    SilentWithProgress: /passive /norestart
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
