PackageIdentifier: BlueJeans.BlueJeans
Publisher: BlueJeans
PackageName: BlueJeans
PackageVersion: 2.26.149.0
License: © 2009-2020 Blue Jeans Network, Inc.. All Rights Reserved.
InstallerType: msi
LicenseUrl: https://www.bluejeans.com/terms-of-service
Moniker: bluejeans
Tags:
- meeting
- conference
- rooms
ShortDescription: Empower Your Remote Workforce with Secure Video Conferencing
PackageUrl: https://www.bluejeans.com/
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://swdl.bluejeans.com/desktop-app/win/2.26.149.0/BlueJeans.2.26.149u.msi
  InstallerSha256: 570C26E35E5DF71CE0942963651FB9506B6420BDE3EBDE677649B0BC2AD7691B
  ProductCode: "{F59022BC-2478-47E7-9D41-5A1190C432FD}"
  InstallerLocale: en-US
  Scope: user
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
