# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 90.1.24.86
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.24.86/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 00F543916AEF8CD66871E48B909B484644571510981689489144A03E9253A587
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.24.86/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 4C2E29E6CA758D57D8B8348EEAE7797861BD0317E34F9A3E229E381C73AEEE62
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

