PackageIdentifier: Dell.CommandUpdate
PackageVersion: 4.0.0
PackageName: Dell Command Update
Publisher: Dell Inc.
License: (c) Dell Inc.
LicenseUrl: https://www.dell.com/learn/us/en/uscorp1/legal_terms-conditions_dellgrmwebpage/art-software-license-agreements
Moniker: DellUpdate
Tags:
- dell
- update
- inspiron
- vostro
- xps
- latitude
- alienware
ShortDescription: Dell Command Update is a stand-alone application for client systems, that provides updates for system software that is released by Dell. This application simplifies the BIOS, firmware, driver, and application update experience for Dell client hardware.
PackageUrl: https://www.dell.com/en-us
Installers:
- Architecture: x86
  InstallerUrl: https://dl.dell.com/FOLDER06747944M/1/Dell-Command-Update-Application_0W0YJ_WIN_4.0.0_A00.EXE
  InstallerSha256: B75FD0ECDFFF40AC0BA68E536D75DAD825CAF5F171CE88D70654D7285A36E1BC
  InstallerType: exe
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
