# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 89.1.22.71
FileExtensions:
  - html
  - htm
  - url
Protocols:
  - http
  - https
Commands:
  - brave
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.22.71/BraveBrowserStandaloneSilentSetup.exe
    InstallerSha256: 548DFB1F2A0E46703423C02F81BAD3E33C0B2D1EBD552FBE4C68ACE91C39E23D
    Scope: machine
    InstallerLocale: en-US
    InstallerSwitches:
      Silent: " "
      SilentWithProgress: " "
    UpgradeBehavior: install
  - Architecture: x86
    InstallerType: exe
    InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.22.71/BraveBrowserStandaloneSilentSetup32.exe
    InstallerSha256: 6d1bba590771224ee93e7038e3eda5bb8ea9cc4727e81444320f20fdd7431c60
    Scope: machine
    InstallerLocale: en-US
    InstallerSwitches:
      Silent: " "
      SilentWithProgress: " "
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
