# Created using wingetcreate

PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 91.1.25.70
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.25.70/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: D9E0568A525E3A86D63EC9EFA2C0609C7F7656F38A84C7797B7280C4CBBB6C59
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.25.70/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 3F65DB34B87FDC8807C10E6455B478DD10A5BC0A585515FC8816A62DEE08E644
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
