# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 89.1.21.70
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: " "
  SilentWithProgress: " "
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.21.70/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 2230F66F9868C3CC5F5C3EC9EEFF0D3DD2405597EEBF83F92E18F8C443B186F5
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.21.70/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 43FA4D7C6013AF77605179D879AD493DD23545309DE49B8C936A7A43FF6EF265
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

