# Created using YamlCreate.ps1 v1.1.5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser-Nightly
PackageVersion: 92.1.29.5
MinimumOSVersion: 10.0.0.0
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.29.5/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 80D69720AB2A33A9F0492320A7689F15713A67951AB7D28CDA8EACCC9DDEFC29
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

