# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 84.1.11.99
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: " "
  SilentWithProgress: " "
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.11.99/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: DB3677F930C1E2788FDAB925BF14F8B2FC0DA0EA5E672FDA461B859B3B45A414
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.11.99/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 55BC38493967D4F41159B8FB6E0922114BEF6A2FBAF878EB4387E54B6260E8BF
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

