PackageIdentifier: BraveSoftware.BraveBrowser
Publisher: The Brave Authors
PackageName: Brave
Moniker: Brave
ShortDescription: Secure, Fast & Private Web Browser with Adblocker
PackageUrl: https://brave.com
Tags:
- Brave
- Browser
- Chrome
- Chromium
License: Mozilla Public License 2.0
LicenseUrl: https://github.com/brave/brave-browser/blob/master/LICENSE
PackageVersion: 81.1.9.76
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.9.76/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 8CA98B4978747E0C2A6F73E429E8D9B12EFD9D3CBBBDC4CB96B4B9AC2AB444AA
  InstallerSwitches:
    Silent: ""
    SilentWithProgress: ""
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
