# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: 7zip.7zip.Alpha.msi
PackageVersion: 21.02.00.0
MinimumOSVersion: 10.0.0.0
Platform:
  - Windows.Desktop
FileExtensions:
  - 7z
  - XZ
  - BZIP2
  - GZIP
  - TAR
  - ZIP
  - AR
  - ARJ
  - CAB
  - CHM
  - CPIO
  - CramFS
  - DMG
  - EXT
  - FAT
  - GPT
  - HFS
  - IHEX
  - ISO
  - LZH
  - LZMA
  - MBR
  - MSI
  - NSIS
  - NTFS
  - QCOW2
  - RAR
  - RPM
  - SquashFS
  - UDF
  - UEFI
  - VDI
  - VHD
  - VMDK
  - WIM
  - XAR
  - Z
Commands:
  - 7z
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  InstallLocation: /D=<INSTALLPATH>
Scope: machine
Installers:
  - Architecture: x64
    InstallerType: msi
    InstallerUrl: https://www.7-zip.org/a/7z2102-x64.msi
    InstallerSha256: 19eb1d7d6307b091f77bef1a4da2e0465cf753e4d1d5dc811640eede4b9afe23
    ProductCode: "{23170F69-40C1-2702-2102-000001000000}"
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
  - Architecture: x86
    InstallerType: msi
    InstallerUrl: https://www.7-zip.org/a/7z2102.msi
    InstallerSha256: 0898beb06fb25c0d98198982a8aeadaea5724330c06b4096abcc1ce656c2c213
    ProductCode: "{23170F69-40C1-2701-2102-000001000000}"
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
