# Automatically updated by the winget bot at 2021/Mar/30
PackageIdentifier: AcroSoftware.CutePDFWriter
PackageVersion: 4.0
PackageName: CutePDF Writer
Publisher: Acro Software Inc.
PackageUrl: http://www.cutepdf.com/Products/CutePDF/writer.asp
License: Copyright © 2003-2020 Acro Software Inc.
ShortDescription: CutePDF Writer, Create PDFs from almost any application
Installers:
- Architecture: x64
  InstallerUrl: https://www.cutepdf.com/download/CuteWriter.exe
  InstallerType: inno
  InstallerSha256: 23122B403212384FB9F5160381B239AA2FAD36EDDF3DA98CE692624D70B2E7DC
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
