PackageIdentifier: Adobe.Brackets
PackageName: Brackets
Moniker: brackets.io
PackageVersion: 0.42
Publisher: Adobe
Author: Adobe
ShortDescription: With focused visual tools and preprocessor support, Brackets is a modern text editor that makes it easy to design in the browser. It's crafted from the ground up for web designers and front-end developers.
License: MIT License
LicenseUrl: https://github.com/adobe/brackets/blob/master/LICENSE
MinimumOSVersion: 10.0.0.0
PackageUrl: http://brackets.io/
Tags:
- brackets
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/adobe/brackets/releases/download/release-0.42/Brackets.Release.0.42.msi
  InstallerSha256: c7e66dd557aa198a7604fcf4ab5b4313485b0abf223577e1ce26267028196875
  InstallerLocale: en-US
  Scope: user
  InstallerSwitches:
    Custom: /QUIET /NORESTART
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0