# Automatically updated by the winget bot at 2021/Jun/23
PackageIdentifier: grammarly.GrammarlyForWindows
PackageVersion: 1.5.75
PackageName: Grammarly
Publisher: Grammarly
License: Copyright (c) Grammarly Inc.
Tags:
- english
- grammar
- checker
ShortDescription: Harness the power of Grammarly on your desktop
PackageUrl: https://www.grammarly.com/native/windows
Installers:
- Architecture: x86
  InstallerUrl: https://download-editor.grammarly.com/windows/GrammarlySetup.exe
  InstallerSha256: 57B46E4FA54563D87943EFF082F08D9D91ACDFF75C3251322BD1E3922EA5F90D
  InstallerType: exe
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
