# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Google.Chrome.Dev
PackageVersion: 93.0.4577.15
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- silent
- silentWithProgress
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise64.msi
  InstallerSha256: BA87E74AFE6402A5A89C098D798DA6EF77364E3F46D4A6C0BCEAB4283F34FDD2
  UpgradeBehavior: install
  ProductCode: '{538DAD3F-2F5D-3E36-9464-2509794B50E2}'
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/dev/googlechromedevstandaloneenterprise.msi
  InstallerSha256: A2D2A2762F22086C034CB2C8F3A9ECD2AC72BBA100F9DCE9E138CFCCB31AE98B
  UpgradeBehavior: install
  ProductCode: '{260F103F-CD13-34F1-84C1-F4D3936E9029}'
ManifestType: installer
ManifestVersion: 1.0.0
