PackageIdentifier: BraveSoftware.BraveBrowser
Publisher: The Brave Authors
PackageName: Brave
Author: Brave Software, Inc.
ShortDescription: Secure, Fast & Private Web Browser with Adblocker
Moniker: Brave
Tags:
- Browser
- Chromium
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
PackageUrl: https://brave.com
License: Mozilla Public License 2.0
LicenseUrl: https://github.com/brave/brave-browser/blob/master/LICENSE
MinimumOSVersion: 10.0.0.0
PackageVersion: 81.1.9.72
InstallerSwitches:
  Custom: ''
  Silent: ""
  SilentWithProgress: ""
InstallerType: exe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.9.72/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 3cab66b6c492d3a213ac09f1c68b3a249bf5a374238c78363e5c98b388ba2624
  Scope: machine
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
