# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 90.1.23.71
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.23.71/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 1DFF2A18BE081BD8F77B4C5D4FFFA2FA11EE890B3D15EED8750109E26B97B840
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.23.71/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: BA55E74B7EC23E3ED730675F99A0D30CD4BC7391C6A670527AA2CF79F9400F42
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

