# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 90.1.24.82
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.24.82/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: B1D80EE8F572C27AD4B70CE5774EDE12B2F7ECCA5C1F624EFD95307D1A2E84CE
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.24.82/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 0EBAD61F05F785A1F413D1F6ECCDB14AB63A653ADB8E9F8AE0A0AB7FF35F3A8D
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

