PackageIdentifier: Anaconda.Miniconda3
PackageName: Miniconda3
Moniker: miniconda3
PackageVersion: py39_4.9.2
Publisher: Anaconda, Inc.
Author: Anaconda
License: BSD 3-Clause License
LicenseUrl: https://docs.conda.io/en/latest/license.html
PackageUrl: https://docs.conda.io/en/latest/miniconda.html
ShortDescription: Miniconda is a free minimal installer for conda.
Tags:
- python
InstallerType: exe
InstallerSwitches:
  Custom: /InstallationType=JustMe /AddToPath=0 /RegisterPython=0
  Silent: /S
  SilentWithProgress: /S
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Windows-x86_64.exe
  InstallerSha256: C3A43D6BC4C4FA92454DBFA636CCB859A045D875DF602B31AE71B9E0C3FEC2B8
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
