PackageIdentifier: BlueJeans.BlueJeans
Publisher: BlueJeans
PackageName: BlueJeans
PackageVersion: 2.28.61.0
License: © 2009-2020 Blue Jeans Network, Inc. All Rights Reserved.
InstallerType: msi
LicenseUrl: https://www.bluejeans.com/terms-of-service
Moniker: bluejeans
Tags:
- meeting
- conference
- rooms
ShortDescription: Empower Your Remote Workforce with Secure Video Conferencing
PackageUrl: https://www.bluejeans.com/
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://swdl.bluejeans.com/desktop-app/win/2.28.61.0/BlueJeans.2.28.61m.msi
  InstallerSha256: fbf290f1800bc1bb416ade532e0a7c783538425b92355c099022945209a08d12
  ProductCode: "{78F337AC-D2D5-4423-8B6D-20FCE8B94407}"
  InstallerLocale: en-US
  Scope: user
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
