PackageIdentifier: Adobe.Brackets
PackageName: Brackets
Moniker: brackets.io
PackageVersion: 1.14.1
Publisher: Adobe
Author: Adobe
ShortDescription: With focused visual tools and preprocessor support, Brackets is a modern text editor that makes it easy to design in the browser. It's crafted from the ground up for web designers and front-end developers.
License: MIT License
LicenseUrl: https://github.com/adobe/brackets/blob/master/LICENSE
MinimumOSVersion: 10.0.0.0
PackageUrl: http://brackets.io/
Tags:
- brackets
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/adobe/brackets/releases/download/release-1.14.1/Brackets.Release.1.14.1.msi
  InstallerSha256: a5b25126acac7a94ef97430b37dc9ab8a628688e1fe21de9317b6d287eb1eb9d
  InstallerLocale: en-US
  Scope: user
  InstallerSwitches:
    Custom: /QUIET /NORESTART
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0