PackageIdentifier: Adobe.Brackets
PackageName: Brackets
Moniker: brackets.io
PackageVersion: 1.5
Publisher: Adobe
Author: Adobe
ShortDescription: With focused visual tools and preprocessor support, Brackets is a modern text editor that makes it easy to design in the browser. It's crafted from the ground up for web designers and front-end developers.
License: MIT License
LicenseUrl: https://github.com/adobe/brackets/blob/master/LICENSE
MinimumOSVersion: 10.0.0.0
PackageUrl: http://brackets.io/
Tags:
- brackets
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/adobe/brackets/releases/download/release-1.5/Brackets.Release.1.5.msi
  InstallerSha256: 35d416a052fc1378f657eb5d6419a6477205e3e1d30a8d8b6da41ecd84803481
  InstallerLocale: en-US
  Scope: user
  InstallerSwitches:
    Custom: /QUIET /NORESTART
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0