# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.0.0.schema.json

PackageIdentifier: Google.Chrome.Beta
PackageVersion: 92.0.4515.107
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
