PackageIdentifier: Anaconda.Miniconda3
PackageName: Miniconda3
Moniker: Miniconda3
PackageVersion: 4.8.3
Publisher: Anaconda
Author: Anaconda
License: BSD 3-Clause License
LicenseUrl: https://docs.conda.io/en/latest/license.html
PackageUrl: https://docs.conda.io/en/latest/miniconda.html
ShortDescription: Miniconda is a free minimal installer for conda.
Tags:
- python
InstallerType: exe
InstallerSwitches:
  Custom: /InstallationType=JustMe /AddToPath=0 /RegisterPython=0
  Silent: /S
  SilentWithProgress: /S
Installers:
- Architecture: x64
  InstallerUrl: https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Windows-x86_64.exe
  InstallerSha256: 6003dbd4d1a9f0c9e64943468d00cf9f6dd2d34cfa0d00c58fe9d175d64c056c
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
