# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 90.1.23.68
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.23.68/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 0E0089C5D12E0FF3E9F10C48C116E7068FEED3AB5190CDABFCA3AFD20F9AC647
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.23.68/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: CA26E7345AF0A8A157C9603CBFA7503E9F94249A9229197253C286B92B6B5528
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

