# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Google.Chrome.Canary
PackageVersion: 94.0.4589.2
PackageLocale: en-US
Publisher: Google LLC
PublisherUrl: https://www.google.com
PublisherSupportUrl: https://support.google.com/?hl=en
PrivacyUrl: https://policies.google.com/privacy?hl=en&fg=1
Author: Google LLC
PackageName: Google Chrome Canary
PackageUrl: https://www.google.com/chrome/canary/
License: Proprietary freeware, based on open source components
LicenseUrl: https://www.google.com/chrome/terms/
Copyright: ©2021 Google
CopyrightUrl: https://www.google.com/chrome/terms/
ShortDescription: Get bleeding edge version of Chrome broswer with Chrome Canary. Be warned - Canary can be unstable.
Description: Get bleeding edge version of Chrome broswer with Chrome Canary. Be warned - Canary can be unstable.
Moniker: chrome-canary
Tags:
- google
- chromium
- browser
- web-browser
- internet-browser
- cross-platform
- canary
ManifestType: defaultLocale
ManifestVersion: 1.0.0
