# Created using wingetcreate

PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 91.1.25.73
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.25.73/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 4E31F96B792643033C102328511FD625C9DD2C3ADE81F6C55E195E50CB0BAE52
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.25.73/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 771C3B9E4C9FC45E805C9A42C3B3F008BCF17DDECBC774D9299BEA863A06C20E
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
