# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 92.0.4515.107
PackageLocale: en-US
Publisher: Google LLC
PublisherUrl: https://www.google.com
PublisherSupportUrl: https://support.google.com/?hl=en
PrivacyUrl: https://policies.google.com/privacy?hl=en&fg=1
Author: Google LLC
PackageName: Google Chrome
PackageUrl: https://www.google.com/chrome
License: Proprietary freeware, based on open source components
LicenseUrl: https://www.google.com/chrome/terms/
Copyright: © 2021 Google, Inc.
CopyrightUrl: https://www.google.com/chrome/terms/
ShortDescription: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
Description: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
Moniker: chrome
Tags:
- google
- chromium
- web
- browser
- web-browser
- internet
- internet-browser
- cross-platform
ManifestType: defaultLocale
ManifestVersion: 1.0.0
