# Created with YamlCreate.ps1 v2.0.0 using YAML parsing
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 92.0.4515.107
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
  InstallerSha256: 5C3A0C9FD305CC34F96905A0D12861CC05F13AFE8EF0ED6E12427E3EACEB4B81
  UpgradeBehavior: install
  ProductCode: '{77B482C4-B8C6-3E7C-A524-3EA1D10CCCD9}'
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
  InstallerSha256: 484E5C7F43A0A62CA37A402569FC2336546C71532C696103B11E8CFA978C46F8
  UpgradeBehavior: install
  ProductCode: '{D1A081BA-14A5-3931-89A9-D19408DD86A5}'
ManifestType: installer
ManifestVersion: 1.0.0
