# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 90.1.24.83
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.24.83/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 277BFEA8CAF4E919CDB1BE1F8A6DC8AA52350DFF919BFB58D3A770C3487DB05C
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.24.83/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 85C9F0CAC9993C33829202B55B1724E088C4035F9BB257DB2B1167E6C766C50A
  Scope: machine
  InstallerLocale: en-US
  InstallerSwitches:
    Silent: " "
    SilentWithProgress: " "
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

