# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Audacity.Audacity.Alpha
PackageVersion: 3.0.3
MinimumOSVersion: 10.0.0.0
FileExtensions:
  - wav
  - aiff
  - pcm
  - flac
  - mp3
  - ogg
  - ogv
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerType: inno
    InstallerUrl: https://github.com/audacity/audacity/releases/download/Audacity-3.0.3-RC2/audacity-win-3.0.3-RC2-x64.exe
    InstallerSha256: 4121FCCBE061DAF894CFF6A6077F65628DEF1E18B475B04A993C8909B5D71582
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
  - Architecture: x86
    InstallerType: inno
    InstallerUrl: https://github.com/audacity/audacity/releases/download/Audacity-3.0.3-RC2/audacity-win-3.0.3-RC2-x86.exe
    InstallerSha256: F403D7C037D3E0FE96AA00F88D7692B438F1364CF0735CBC26E854C76DAEE7F5
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
