# Automatically updated by the winget bot at 2021/May/28
PackageIdentifier: Foxit.PhantomPDF
Publisher: Foxit
PackageName: PhantomPDF
PackageVersion: 11.0.0.49893
License: 2020 © Foxit Software Incorporated. All rights reserved.
InstallerType: exe
Moniker: FoxitPhantomPDF
Tags:
- PDF
- Foxit
ShortDescription: PhantomPDF is the PDF Editor that enables PDF document accessibility for people with disabilities who use assistive technology to have access to information.
PackageUrl: https://www.foxitsoftware.com/pdf-editor/
Installers:
- Architecture: x86
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/11.0.0/FoxitEditor110_L10N_Setup_Website.exe
  InstallerSha256: 28DFCFA6457979D2E7E449B9BBF4DA0336A7F82969E9328222802E23F9824A26
  InstallerSwitches:
    Silent: /silent
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
