PackageIdentifier: Dell.CommandUpdate
PackageVersion: 4.1.0
PackageName: Dell Command Update
Publisher: Dell Inc.
License: (c) Dell Inc.
LicenseUrl: https://www.dell.com/learn/us/en/uscorp1/legal_terms-conditions_dellgrmwebpage/art-software-license-agreements
Moniker: DellCommandUpdate
Tags:
- dell
- update
- inspiron
- vostro
- xps
- latitude
- alienware
ShortDescription: Dell Command Update is a stand-alone application for client systems, that provides updates for system software that is released by Dell. This application simplifies the BIOS, firmware, driver, and application update experience for Dell client hardware.
PackageUrl: https://www.dell.com/en-us
Installers:
- Architecture: x86
  InstallerUrl: https://dl.dell.com/FOLDER06986400M/1/Dell-Command-Update-Application_P5R35_WIN_4.1.0_A00.EXE
  InstallerSha256: 351DEC8E58272639D9A78E58F3A8A72AB189B635A946869848EE62986F85436A
  InstallerType: exe
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
