# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 92.1.27.106
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- brave
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.27.106/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: ACBEA04AFD3B81D5CEE7BC361C4594ED3CB7AA0E14F41E10E907A9D028189F0D
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.27.106/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: 769874618245D764E46405F2B74A71B7D1619D57ED711516DF2A6CADAD6FE616
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

