# Automatically updated by the winget bot at 2021/Apr/02
PackageIdentifier: grammarly.grammarlyforoffice
PackageName: Grammarly for Microsoft® Office Suite
PackageVersion: 6.8.261
Publisher: Grammarly
License: copyright (c) grammarly
ShortDescription: Grammarly automatically detects potential grammar, spelling, punctuation, word choice, tone and style mistakes in writing, following standard linguistic prescription.
Tags:
- microsoft office
- document
- office extension
- english
- grammar
- checker
PackageUrl: https://www.grammarly.com/office-addin
Moniker: grammarlyforoffice
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://download-office.grammarly.com/latest/GrammarlyAddInSetup.exe
  InstallerSha256: F11891A6A2FBD5DA55C21DBA1172D8C9A610A8FB96F3FCFD4BBB186D4C0E221A
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
