PackageIdentifier: Anaconda.Anaconda3
Publisher: Anaconda
PackageName: Anaconda Individual Edition
PackageVersion: 2020.11
License: BSD 3-Clause License
InstallerType: exe
LicenseUrl: https://docs.conda.io/en/latest/license.html
Moniker: Anaconda3
Tags:
- Python
- conda
ShortDescription: Anaconda Individual Edition is the easiest way to perform Python/R data science and machine learning on a single machine. Developed for solo practitioners, it is the toolkit that equips you to work with thousands of open-source packages and libraries.
PackageUrl: https://www.anaconda.com/products/individual
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://repo.anaconda.com/archive/Anaconda3-2020.11-Windows-x86_64.exe
  InstallerSha256: AA523115DAF31C431BB392FAF75E70D35ADA935E36DC7B1DD8902BAEE240BCC1
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
