# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 89.1.21.77
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: " "
  SilentWithProgress: " "
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.21.77/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 099E6D7E417D58EBA59DD94AC6020228845AA15BBE43D52B33321B5335943500
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.21.77/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: FC119F47FA9C9E829D5D8417B0C96F777B5AFE5120D10B43A802A0F0E82A2014
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

