# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 89.1.21.73
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: " "
  SilentWithProgress: " "
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.21.73/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 6F75338B33C850DB6E6C62A1A19A6B3C8FC06CF4B1C9F0D97AA2FD84C6E468AA
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.21.73/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: E9EA1082B1F71A34B9B7FCD59B55CCEA95580C278BC4E877AA574A5BC44AC4F7
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

