PackageIdentifier: Adobe.Brackets
PackageName: Brackets
Moniker: brackets.io
PackageVersion: 1.13
Publisher: Adobe
Author: Adobe
ShortDescription: With focused visual tools and preprocessor support, Brackets is a modern text editor that makes it easy to design in the browser. It's crafted from the ground up for web designers and front-end developers.
License: MIT License
LicenseUrl: https://github.com/adobe/brackets/blob/master/LICENSE
MinimumOSVersion: 10.0.0.0
PackageUrl: http://brackets.io/
Tags:
- brackets
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/adobe/brackets/releases/download/release-1.13/Brackets.Release.1.13.msi
  InstallerSha256: 1d9879807aef35a322e9129e0692fcc7d1d2704daab6d5c65767ede23d3c7384
  InstallerLocale: en-US
  Scope: user
  InstallerSwitches:
    Custom: /QUIET /NORESTART
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0