# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 86.1.15.69
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: " "
  SilentWithProgress: " "
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.15.69/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: 509F5EED59F051E968818344F9BF51201FFC8C5E7E6D0D298C15E6754F799ADF
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.15.69/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: C4F13DD56D8453E874506BF1804CE26B186CAFA2A38C8BF301396CF67A311164
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

