# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Google.Chrome.Beta
PackageVersion: 93.0.4577.18
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 0E297CABD853263CAEC9957FAB6013E29231DD9B5A211947EC4BDB25DE60F068
  UpgradeBehavior: install
  ProductCode: "{7A0391BB-7492-3F15-BA8A-57B936847CFC}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 22942411FAF0B2AA256AD0F76877E282DBB433378F834E406E918C9C29320256
  UpgradeBehavior: install
  ProductCode: "{5A3CFE43-2598-335D-B2C9-A20E23BA17FF}"
ManifestType: installer
ManifestVersion: 1.0.0

