# Created using YamlCreate.ps1 v1.1.5
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser
PackageVersion: 91.1.26.77
MinimumOSVersion: 10.0.0.0
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- brave
InstallModes:
- silent
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.26.77/BraveBrowserStandaloneSilentSetup.exe
  InstallerSha256: F28910EE67363A03AD7C59D8802562B0CFCDD6B051128137699AAE911A132DCD
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.26.77/BraveBrowserStandaloneSilentSetup32.exe
  InstallerSha256: A41D02527B81788C82E6C23C99DEBA89B1382716A7A35AA9AA3ADDD9E9FD240E
  InstallerSwitches:
    Silent: ' '
    SilentWithProgress: ' '
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

